version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123*
      POSTGRES_DB: eventplatform
    ports:
      - "5432:5432"
    volumes:
      # Persistencia de datos, crea el folder si no existe
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventplatform"]
      interval: 10s
      timeout: 5s
      retries: 5